# Generated by Django 6.0.2 on 2026-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReviewCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.PositiveIntegerField(db_index=True)),
                ('recipient_type', models.CharField(choices=[('employer', 'Employer'), ('learner', 'Learner'), ('qa_system', 'Quality Assurance system')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
