# MCR file header: Backend\mcr\migrations\0003_remove_communication_log.py
# This file is part of the MCR application source.
# Purpose: Remove Communication Log models.


# Generated by Django 6.0.2 on 2026-04-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcr", "0002_dashboard_review_communication"),
    ]

    operations = [
        migrations.DeleteModel(name="DashboardReviewCommunication"),
        migrations.DeleteModel(name="CommunicationLogEntry"),
    ]

