# Generated by Django 6.0.2 on 2026-03-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McrReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('programme', models.CharField(blank=True, default='', max_length=200)),
                ('group', models.CharField(blank=True, default='', max_length=200)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('total_duration_min', models.PositiveIntegerField(default=0)),
                ('coach_name', models.CharField(max_length=200)),
                ('learner_name', models.CharField(max_length=200)),
                ('rag_status', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='amber', max_length=10)),
                ('qualitative_rating', models.CharField(choices=[('outstanding', 'Outstanding'), ('strong', 'Strong'), ('requires_improvement', 'Requires Improvement'), ('cause_for_concern', 'Cause for Concern')], default='strong', max_length=30)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_development', models.TextField(blank=True, default='')),
                ('professional_judgement', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('verified', models.BooleanField(default=False)),
                ('ksb_tags', models.JSONField(blank=True, default=list)),
                ('epa_topics', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='mcr.mcrreview')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('employer', 'Employer'), ('learner', 'Learner'), ('qa_system', 'Quality Assurance system')], max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('sent_by', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='mcr.mcrreview')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, default='', max_length=80)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mcr.mcrreview')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSectionTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=80)),
                ('section_name', models.CharField(max_length=200)),
                ('planned_min', models.PositiveIntegerField()),
                ('actual_min', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_timings', to='mcr.mcrreview')),
            ],
        ),
        migrations.CreateModel(
            name='QaIndicatorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(max_length=80)),
                ('indicator_name', models.CharField(max_length=200)),
                ('score0to5', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('met', 'Met'), ('partial', 'Partially Met'), ('not_met', 'Not Met')], default='partial', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_indicators', to='mcr.mcrreview')),
            ],
        ),
        migrations.CreateModel(
            name='SafeguardingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('met', 'Met'), ('partial', 'Partially Met'), ('not_met', 'Not Met')], default='partial', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_items', to='mcr.mcrreview')),
            ],
        ),
    ]
